//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPhotoPrintingEproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FrameTable()
        {
            this.OrderTable = new HashSet<OrderTable>();
        }
    
        public int f_Id { get; set; }
        public string f_Image { get; set; }
        public string f_Size { get; set; }
        public Nullable<decimal> f_Price { get; set; }
        public string f_Type { get; set; }
        public string f_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTable { get; set; }
    }
}
