//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPhotoPrintingEproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int o_Id { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> mg_Id { get; set; }
        public Nullable<int> f_Id { get; set; }
        public string o_Size_ { get; set; }
        public Nullable<System.DateTime> o_Date { get; set; }
        public Nullable<int> o_Quantity { get; set; }
        public string o_Address { get; set; }
        public Nullable<decimal> o_Price { get; set; }
        public Nullable<decimal> o_TotalPrice { get; set; }
    
        public virtual FrameTable FrameTable { get; set; }
        public virtual GelleryTable GelleryTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
